### PR TITLE
Clean up A' generation

### PR DESCRIPTION
**Pull request by cmantill**
@Duchstf @yongbinfeng as we discussed before, here I'm trying out a simple modification in the code. This just modifies the number of times we sample events (so that we don't favor any particular couplings).
@Duchstf the only question I have is how many times to sample (I fixed it to 10e4 for now). Got any input on this?
Thanks!

(Just realized this also integrates the trimuon generation in the code)

### CODE REVIEW

**Comment by Duchstf** [comment]
@cmantill Could you explain what "number of times we sample events" mean? I chat with Yongbin and both of us are not sure about what you are specifically referring to so if you can elaborate more on this that would be great!!

**Comment by cmantill** [comment]
@Duchstf I fixed things up in my last commit. Here is my explanation of (1) how things used to work and (2) what I propose in this PR:

(1) We used to take our vector of input events and loop over them. Every time we looped over one event, we would obtain a vertex displacement based on the kinematics (beta) and decay length of that A'. If that vertex was within our bounds (e.g. 5-6m) we kept it and saved as a HepMC event. If not, we discarded it. The trick was that we put an exit condition on our loop over input events if we reached a certain number of events or if we sampled a given number of times.

I think this is biasing our signal distributions towards regions of higher acceptance in that vertex displacement. That is, for events with mass and coupling where it's lifetime favors 5-6m it would be easy to reach the certain number of events and most likely the number of sampling times ~= number of generated displaced events. For events with mass and coupling (and lifetime) unlikely to decay in that region in z (e.g. 5-6m) we would have to sample many more times until we get the required number of events (or sometimes not even that). This would make the kinematics of the displaced events more likely to be boosted (or just different than the input events) for those lower couplings.

(2) To avoid any bias, we just sample each event a fixed number of times. 

I have kept option (1) in the code but is not set to False as default (`fixedEvents`). 

Let me know if this makes sense

**Comment by cmantill** [comment]
hi @Duchstf @yongbinfeng , I added a weight to the new outputs, e.g. see an example here `/seaquest/users/cmantill/DarkQuest/lhe/output/displaced_Aprime_Muons/Eta_0.530000_z500_600_eps_-6.6.txt`.  And this main commit: https://github.com/DarkQuest-FNAL/DarkQuest/pull/24/commits/c118ce872a8187149c3ef41d5fec80c797825698 and added it to the macro as well: https://github.com/DarkQuest-FNAL/DarkQuest/pull/24/commits/1ef17a56541a8349320fd5ca4475b89bdfd32297

For now I have omitted the cross section weight (but put a comment on what I think it should be) - can you review and provide comments?

**Comment by yongbinfeng** [comment]
Hi @cmantill thanks a lot! looks good to me. I'll run some tests later today. From a first look, if the weights based on the sampling times are already calculated and then applied on each event, do we still need a cross section weight?

**Pull request merged**
